name: Build and Test Plugin

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and Test
        run: |
            chmod u+x ./gradlew
            ./gradlew :gradle-plugin:build :gradle-plugin:test :gradle-plugin:testFunc --info --stacktrace
